"""The `from <module> import *` statements caller code is allowed to keep.

Caller imports are refused by default (item 27): an import is how you get back
everything the namespace scrub removed. But a great deal of idiomatic Sage --
and 1,546 examples in SageMath's own doctests -- opens with a star import of an
*internal* module whose public names are all ordinary mathematics:
`from sage.matroids.lean_matrix import *`. Those names are not dangerous; they
are simply not what `sage.all` chose to export, so the namespace does not hold
them and the import is the only way to reach them.

This is the curated, reviewed exception. For each module here, every public
name passed the same danger screen the namespace scrub applies -- clean as a
whole or excluded entirely, never filtered. `rewrite_permitted_imports` expands
`from <module> import *` into the explicit list below before validation, so what
runs is exactly what was screened, and the names become the caller's to read
the way any name they bind does. Nothing is added to the allowlist and the
allowlist is never suspended.

Generated by scripts/generate_star_exports.py; checked against the installed
Sage by an integration test. Do not edit by hand -- a module that gains a
name reaching a shell, compiler, pickle or file belongs out of the curated
list, not filtered here.
"""

from __future__ import annotations

STAR_EXPORTS: dict[str, frozenset[str]] = {

    "sage.matroids.lean_matrix": frozenset({
        "BinaryMatrix", "GF", "GenericMatrix", "LeanMatrix", "PlusMinusOneMatrix",
        "QQ", "QuaternaryMatrix", "RationalMatrix", "TernaryMatrix", "ZZ",
        "bytes_to_str", "generic_identity", "have_same_parent", "matrix", "parent",
        "str_to_bytes"
    }),
    "sage.graphs.graph_decompositions.modular_decomposition": frozenset({
        "IntEnum", "Node", "NodeType", "PermutationGroupElement", "bytes_to_str",
        "check_algos_are_equivalent", "check_gamma_modules",
        "check_maximal_modules", "check_modular_decomposition", "check_module",
        "children_node_type", "corneil_habib_paul_tedder_algorithm",
        "either_connected_or_not_connected", "equivalent_trees", "form_module",
        "gamma_classes", "get_module_type", "get_vertices",
        "habib_maurer_algorithm", "md_tree_to_graph", "modular_decomposition",
        "nested_tuple_to_tree", "permute_decomposition", "print_md_tree",
        "random_md_tree", "random_testing", "recreate_decomposition",
        "relabel_tree", "str_to_bytes", "tree_to_nested_tuple"
    }),
    "sage.coding.binary_code": frozenset({
        "BinaryCode", "BinaryCodeClassifier", "OrbitPartition", "PartitionStack",
        "WORD_SIZE", "bytes_to_str", "cputime", "have_same_parent", "parent",
        "str_to_bytes", "test_expand_to_ortho_basis", "test_word_perms",
        "weight_dist"
    }),
    "sage.combinat.sf.kfpoly": frozenset({
        "KostkaFoulkesPolynomial", "SemistandardSkewTableaux", "SkewPartitions",
        "ZS1_iterator", "ZZ", "compat", "dom", "kfpoly", "kfpoly_skew", "polygen",
        "riggings", "schur_to_hl", "weight"
    }),
    "sage.schemes.elliptic_curves.weierstrass_morphism": frozenset({
        "EllipticCurve", "EllipticCurveHom", "Integer", "PolynomialRing",
        "Sequence", "WeierstrassIsomorphism", "baseWI", "get_coercion_model",
        "identity_morphism", "negation_morphism", "op_EQ", "op_NE", "richcmp",
        "richcmp_not_equal"
    }),
    "sage.libs.lcalc.lcalc_Lfunction": frozenset({
        "CCC", "ComplexField", "Lfunction", "Lfunction_C", "Lfunction_D",
        "Lfunction_I", "Lfunction_Zeta", "Lfunction_from_character",
        "Lfunction_from_elliptic_curve", "RRR", "RealField", "bytes_to_str",
        "have_same_parent", "parent", "pi", "str_to_bytes"
    }),
    "sage.plot.plot3d.shapes": frozenset({
        "Box", "ColorCube", "Cone", "Cylinder", "Graphics3dGroup", "LineSegment",
        "RDF", "Sphere", "Text", "Torus", "arrow3d", "rename_keyword",
        "validate_frame_size", "vector"
    }),
    "sage.matroids.union_matroid": frozenset({
        "MatroidSum", "MatroidUnion", "PartitionMatroid", "bytes_to_str",
        "str_to_bytes"
    }),
    "sage.modules.fp_graded.module": frozenset({
        "FPElement", "FPModule", "FreeGradedModule", "FreeGradedModuleElement",
        "GradedModules", "Hom", "IndexedGenerators", "Module", "Morphism",
        "UniqueRepresentation", "cached_method", "infinity", "lazy_attribute",
        "parent"
    }),
    "sage.combinat.dlx": frozenset({
        "AllExactCovers", "COLUMN", "COUNT", "DLXMatrix", "DOWN", "INDEX", "LEFT",
        "OneExactCover", "RIGHT", "ROOTNODE", "UP"
    }),
    "sage.rings.fraction_field_FpT": frozenset({
        "FpT", "FpTElement", "FpT_Fp_section", "FpT_Polyring_section", "FpT_iter",
        "Fp_FpT_coerce", "FractionField_1poly_field", "Polyring_FpT_coerce", "ZZ",
        "ZZ_FpT_coerce", "have_same_parent", "parent", "revop", "rich_to_bool",
        "rich_to_bool_sgn", "richcmp", "richcmp_not_equal", "unpickle_FpT_element"
    }),
}

