"""The `from <module> import *` statements caller code is allowed to keep.

Caller imports are refused by default (item 27): an import is how you get back
everything the namespace scrub removed. But a great deal of idiomatic Sage --
and 1,546 examples in SageMath's own doctests -- opens with a star import of an
*internal* module whose public names are all ordinary mathematics:
`from sage.matroids.lean_matrix import *`. Those names are not dangerous; they
are simply not what `sage.all` chose to export, so the namespace does not hold
them and the import is the only way to reach them.

This is the curated, reviewed exception. For each module here, every public
name passed the same danger screen the namespace scrub applies -- clean as a
whole or excluded entirely, never filtered. `rewrite_permitted_imports` expands
`from <module> import *` into the explicit list below before validation, so what
runs is exactly what was screened, and the names become the caller's to read
the way any name they bind does. Nothing is added to the allowlist and the
allowlist is never suspended.

Generated by scripts/generate_star_exports.py; checked against the installed
Sage by an integration test. Do not edit by hand -- a module that gains a
name reaching a shell, compiler, pickle or file belongs out of the curated
list, not filtered here.
"""

from __future__ import annotations

STAR_EXPORTS: dict[str, frozenset[str]] = {

    "sage.rings.polynomial.real_roots": frozenset({
        "AA", "FreeModule", "MatrixSpace", "PolynomialRing", "PrecisionError", "QQ",
        "RDF", "RIF", "RR", "RealField", "RealIntervalField", "ZZ",
        "bernstein_down", "bernstein_expand", "bernstein_polynomial_factory",
        "bernstein_polynomial_factory_ar", "bernstein_polynomial_factory_intlist",
        "bernstein_polynomial_factory_ratlist", "bernstein_up", "binomial",
        "bitsize_doctest", "cl_maximum_root", "cl_maximum_root_first_lambda",
        "cl_maximum_root_local_max", "context", "copy", "de_casteljau_doublevec",
        "de_casteljau_intvec", "degree_reduction_next_size", "denominator",
        "dprod_imatrow_vec", "dr_cache", "factorial", "get_realfield_rndu",
        "have_same_parent", "infinity", "interval_bernstein_polynomial",
        "interval_bernstein_polynomial_float",
        "interval_bernstein_polynomial_integer", "intvec_to_doublevec", "island",
        "linear_map", "lmap", "max_abs_doublevec", "max_bitsize_intvec_doctest",
        "maximum_root_first_lambda", "maximum_root_local_max",
        "min_max_delta_intvec", "min_max_diff_doublevec", "min_max_diff_intvec",
        "mk_context", "mk_ibpf", "mk_ibpi", "numerator", "ocean", "parent",
        "precompute_degree_reduction_cache", "prod", "pseudoinverse", "randstate",
        "rational_root_bounds", "real_roots", "realfield_rndu_cache",
        "relative_bounds", "reverse_intvec", "root_bounds", "rr_gap",
        "scale_intvec_var", "split_for_targets", "subsample_vec_doctest",
        "taylor_shift1_intvec", "to_bernstein", "to_bernstein_warp", "vector",
        "warp_map", "wordsize_rational"
    }),
    "sage.matroids.lean_matrix": frozenset({
        "BinaryMatrix", "GF", "GenericMatrix", "LeanMatrix", "PlusMinusOneMatrix",
        "QQ", "QuaternaryMatrix", "RationalMatrix", "TernaryMatrix", "ZZ",
        "bytes_to_str", "generic_identity", "have_same_parent", "matrix", "parent",
        "str_to_bytes"
    }),
    "sage.graphs.graph_decompositions.modular_decomposition": frozenset({
        "IntEnum", "Node", "NodeType", "PermutationGroupElement", "bytes_to_str",
        "check_algos_are_equivalent", "check_gamma_modules",
        "check_maximal_modules", "check_modular_decomposition", "check_module",
        "children_node_type", "corneil_habib_paul_tedder_algorithm",
        "either_connected_or_not_connected", "equivalent_trees", "form_module",
        "gamma_classes", "get_module_type", "get_vertices",
        "habib_maurer_algorithm", "md_tree_to_graph", "modular_decomposition",
        "nested_tuple_to_tree", "permute_decomposition", "print_md_tree",
        "random_md_tree", "random_testing", "recreate_decomposition",
        "relabel_tree", "str_to_bytes", "tree_to_nested_tuple"
    }),
    "sage.coding.binary_code": frozenset({
        "BinaryCode", "BinaryCodeClassifier", "OrbitPartition", "PartitionStack",
        "WORD_SIZE", "bytes_to_str", "copy", "cputime", "have_same_parent",
        "parent", "str_to_bytes", "test_expand_to_ortho_basis", "test_word_perms",
        "weight_dist"
    }),
    "sage.combinat.sf.kfpoly": frozenset({
        "KostkaFoulkesPolynomial", "SemistandardSkewTableaux", "SkewPartitions",
        "ZS1_iterator", "ZZ", "compat", "dom", "kfpoly", "kfpoly_skew", "polygen",
        "riggings", "schur_to_hl", "weight"
    }),
    "sage.modular.dims": frozenset({
        "ArithmeticSubgroup", "CO_delta", "CO_nu", "CohenOesterle", "Gamma0",
        "Gamma1", "GammaH_class", "Integer", "IntegerModRing", "Mod",
        "dimension_cusp_forms", "dimension_eis", "dimension_modular_forms",
        "dimension_new_cusp_forms", "eisen", "factor", "frac", "is_prime", "prod",
        "sturm_bound", "valuation"
    }),
    "sage.schemes.elliptic_curves.weierstrass_morphism": frozenset({
        "EllipticCurve", "EllipticCurveHom", "Integer", "PolynomialRing",
        "Sequence", "WeierstrassIsomorphism", "baseWI", "get_coercion_model",
        "identity_morphism", "negation_morphism", "op_EQ", "op_NE", "richcmp",
        "richcmp_not_equal"
    }),
    "sage.libs.lcalc.lcalc_Lfunction": frozenset({
        "CCC", "ComplexField", "Lfunction", "Lfunction_C", "Lfunction_D",
        "Lfunction_I", "Lfunction_Zeta", "Lfunction_from_character",
        "Lfunction_from_elliptic_curve", "RRR", "RealField", "bytes_to_str",
        "have_same_parent", "parent", "pi", "str_to_bytes"
    }),
    "sage.plot.plot3d.shapes": frozenset({
        "Box", "ColorCube", "Cone", "Cylinder", "Graphics3dGroup", "LineSegment",
        "RDF", "Sphere", "Text", "Torus", "arrow3d", "rename_keyword",
        "validate_frame_size", "vector"
    }),
    "sage.matroids.union_matroid": frozenset({
        "MatroidSum", "MatroidUnion", "PartitionMatroid", "bytes_to_str",
        "str_to_bytes"
    }),
    "sage.modules.fp_graded.module": frozenset({
        "FPElement", "FPModule", "FreeGradedModule", "FreeGradedModuleElement",
        "GradedModules", "Hom", "IndexedGenerators", "Module", "Morphism",
        "UniqueRepresentation", "cached_method", "infinity", "lazy_attribute",
        "parent"
    }),
    "sage.combinat.dlx": frozenset({
        "AllExactCovers", "COLUMN", "COUNT", "DLXMatrix", "DOWN", "INDEX", "LEFT",
        "OneExactCover", "RIGHT", "ROOTNODE", "UP"
    }),
    "sage.rings.fraction_field_FpT": frozenset({
        "FpT", "FpTElement", "FpT_Fp_section", "FpT_Polyring_section", "FpT_iter",
        "Fp_FpT_coerce", "FractionField_1poly_field", "Polyring_FpT_coerce", "ZZ",
        "ZZ_FpT_coerce", "have_same_parent", "parent", "revop", "rich_to_bool",
        "rich_to_bool_sgn", "richcmp", "richcmp_not_equal", "unpickle_FpT_element"
    }),
    "sage.rings.polynomial.pbori.pbori": frozenset({
        "BooleConstant", "BooleSet", "BooleSetIterator", "BooleanMonomial",
        "BooleanMonomialIterator", "BooleanMonomialMonoid",
        "BooleanMonomialVariableIterator", "BooleanMulAction", "BooleanPolynomial",
        "BooleanPolynomialEntry", "BooleanPolynomialIdeal",
        "BooleanPolynomialIterator", "BooleanPolynomialRing",
        "BooleanPolynomialVector", "BooleanPolynomialVectorIterator",
        "CCuddNavigator", "ClasscallMetaclass", "FGLMStrategy", "FieldIdeal", "GF",
        "GroebnerStrategy", "Integer", "MPolynomialIdeal", "Monoid_class",
        "Monomial", "MonomialConstruct", "MonomialFactory", "OrderCode",
        "Polynomial", "PolynomialConstruct", "PolynomialFactory", "PolynomialRing",
        "PolynomialRing_generic", "ReductionStrategy", "Sequence", "TermOrder",
        "TermOrder_from_pb_order", "Variable", "VariableBlock", "VariableConstruct",
        "VariableFactory", "add_up_polynomials", "block_dlex", "block_dp_asc",
        "bytes_to_str", "coerce_binop", "contained_vars", "current_randstate",
        "dlex", "dp", "dp_asc", "easy_linear_factors", "gauss_on_polys",
        "get_var_mapping", "have_same_parent", "if_then_else", "interpolate",
        "interpolate_smallest_lex", "inv_order_dict", "ll_red_nf_noredsb",
        "ll_red_nf_noredsb_single_recursive_call", "ll_red_nf_redsb", "lp",
        "map_every_x_to_x_plus_one", "mod_mon_set", "mod_var_set",
        "mult_fact_sim_C", "nf3", "order_dict", "order_mapping", "parallel_reduce",
        "parent", "random_set", "recursively_insert", "red_tail", "revop",
        "rich_to_bool", "rich_to_bool_sgn", "richcmp", "richcmp_not_equal", "rings",
        "set_random_seed", "str_to_bytes", "substitute_variables", "top_index",
        "typecall", "unpickle_BooleanPolynomial", "unpickle_BooleanPolynomial0",
        "unpickle_BooleanPolynomialRing", "zeros"
    }),
    "sage.rings.polynomial.pbori": frozenset({
        "AlternatingBlock", "Block", "HigherOrderBlock", "Monomial", "Polynomial",
        "Ring", "Variable", "all_monomials_of_degree_d", "declare_ring",
        "groebner_basis", "load_file", "normal_form", "power_set"
    }),
    "sage.matroids.advanced": frozenset({
        "BasisMatroid", "BinaryMatroid", "CircuitClosuresMatroid",
        "CircuitsMatroid", "DualMatroid", "FlatsMatroid", "GraphicMatroid",
        "LinearMatroid", "LinearSubclasses", "MatroidExtensions", "MatroidSum",
        "MatroidUnion", "MinorMatroid", "PartitionMatroid", "QuaternaryMatroid",
        "RankMatroid", "RegularMatroid", "TernaryMatroid", "cmp_elements_key",
        "get_nonisomorphic_matroids", "lift_cross_ratios", "lift_map", "newlabel",
        "setprint"
    }),
    "sage.combinat.matrices.latin": frozenset({
        "DLXCPP", "FiniteField", "GapElement", "Integer", "LatinSquare",
        "LatinSquare_generator", "Matrix_integer_dense", "Permutation",
        "PermutationConstructor", "PermutationGroup", "PermutationGroupElement",
        "ZZ", "alternating_group_bitrade_generators", "back_circulant", "beta1",
        "beta2", "beta3", "bitrade", "bitrade_from_group", "cells_map_as_square",
        "check_bitrade_generators", "coin", "column_containing_sym",
        "direct_product", "dlxcpp_find_completions", "dlxcpp_rows_and_map",
        "elementary_abelian_2group", "flatten", "forward_circulant", "genus",
        "group_to_LatinSquare", "is_bitrade", "is_disjoint", "is_primary_bitrade",
        "is_prime", "is_row_and_col_balanced", "is_same_shape", "isotopism",
        "matrix", "next_conjugate", "p3_group_bitrade_generators",
        "pq_group_bitrade_generators", "reduce", "row_containing_sym", "tau1",
        "tau123", "tau2", "tau3", "tau_to_bitrade"
    }),
    "sage.graphs.generators.distance_regular": frozenset({
        "AlternatingFormsGraph", "BiggsSmithGraph", "BilinearFormsGraph",
        "ConwaySmith_for_3S7", "CoxeterGraph", "DodecahedralGraph",
        "DoubleGrassmannGraph", "DoubleOddGraph", "DoublyTruncatedWittGraph",
        "FosterGraph", "FosterGraph3S6", "GF", "GeneralisedDodecagonGraph",
        "GeneralisedHexagonGraph", "GeneralisedOctagonGraph", "GossetGraph",
        "Graph", "GrassmannGraph", "HalfCube", "HermitianFormsGraph",
        "HigmanSimsGraph", "HoffmanSingletonGraph", "IvanovIvanovFaradjevGraph",
        "J2Graph", "LargeWittGraph", "LeonardGraph", "LivingstoneGraph", "Matrix",
        "SimsGewirtzGraph", "TruncatedWittGraph", "UstimenkoGraph", "VectorSpace",
        "WellsGraph", "cocliques_HoffmannSingleton",
        "distance_3_doubly_truncated_Golay_code_graph", "distance_regular_graph",
        "graph_3O73", "graph_from_GQ_spread", "graph_with_classical_parameters",
        "is_classical_parameters_graph", "is_from_GQ_spread", "is_near_polygon",
        "is_pseudo_partition_graph", "locally_GQ42_distance_transitive_graph",
        "near_polygon_graph", "pseudo_partition_graph",
        "shortened_000_111_extended_binary_Golay_code_graph",
        "shortened_00_11_binary_Golay_code_graph", "strongly_regular_graph",
        "vanLintSchrijverGraph", "vector"
    }),
    "sage.tests.arxiv_0812_2725": frozenset({
        "CompleteMatchings", "SetPartitions", "dcrossing", "dcrossvec_cm",
        "dcrossvec_setp", "matchingsset", "setp_to_edges", "tablecolumn"
    }),
    "sage.combinat.designs.gen_quadrangles_with_spread": frozenset({
        "dual_GQ_ovoid", "generalised_quadrangle_hermitian_with_ovoid",
        "generalised_quadrangle_with_spread", "is_GQ_with_spread"
    }),
    "sage.manifolds.operators": frozenset({
        "curl", "dalembertian", "div", "grad", "laplacian"
    }),
    "sage.structure.set_factories": frozenset({
        "BareFunctionPolicy", "FacadeParentPolicy", "Parent",
        "ParentWithSetFactory", "SageObject", "SelfParentPolicy", "SetFactory",
        "SetFactoryPolicy", "TopMostParentPolicy", "UniqueRepresentation",
        "abstract_method"
    }),
    "sage.structure.set_factories_example": frozenset({
        "AllPairs", "DisjointUnionEnumeratedSets", "ElementWrapper",
        "EnumeratedSets", "Integer", "LazyFamily", "MAX", "PairsX_", "Pairs_Y",
        "ParentWithSetFactory", "SetFactory", "SingletonPair",
        "TopMostParentPolicy", "UniqueRepresentation", "XYPair", "XYPairs",
        "XYPairsFactory", "lazy_attribute"
    }),
    "sage.typeset.symbols": frozenset({
        "CompoundAsciiSymbol", "CompoundSymbol", "CompoundUnicodeSymbol",
        "SageObject", "ascii_integral", "ascii_left_curly_brace",
        "ascii_left_parenthesis", "ascii_left_square_bracket",
        "ascii_right_curly_brace", "ascii_right_parenthesis",
        "ascii_right_square_bracket", "unicode_integral",
        "unicode_left_curly_brace", "unicode_left_parenthesis",
        "unicode_left_square_bracket", "unicode_right_curly_brace",
        "unicode_right_parenthesis", "unicode_right_square_bracket"
    }),
    "sage.algebras.exterior_algebra_groebner": frozenset({
        "GBElement", "GroebnerStrategy", "GroebnerStrategyDegLex",
        "GroebnerStrategyDegRevLex", "GroebnerStrategyNegLex", "bytes_to_str",
        "copy", "have_same_parent", "parent", "revop", "rich_to_bool",
        "rich_to_bool_sgn", "richcmp", "richcmp_not_equal", "str_to_bytes"
    }),
    "sage.combinat.species.library": frozenset({
        "BinaryForestSpecies", "BinaryTreeSpecies", "CharacteristicSpecies",
        "CombinatorialSpecies", "CompositionSpecies", "CycleSpecies",
        "EmptySetSpecies", "EmptySpecies", "FunctorialCompositionSpecies",
        "LinearOrderSpecies", "PartitionSpecies", "PermutationSpecies",
        "ProductSpecies", "SetSpecies", "SimpleGraphSpecies", "SingletonSpecies",
        "SubsetSpecies", "SumSpecies"
    }),
    "sage.schemes.toric.fano_variety": frozenset({
        "AlgebraicScheme_subscheme_toric", "AnticanonicalHypersurface",
        "CPRFanoToricVariety", "CPRFanoToricVariety_field", "Cone",
        "DEFAULT_COEFFICIENT", "DEFAULT_COEFFICIENTS", "FaceFan", "Fan", "Fields",
        "FractionField_generic", "LatticePolytope", "MPolynomialRing_base",
        "NefCompleteIntersection", "PolynomialRing", "PolynomialRing_generic", "QQ",
        "ToricVariety_field", "add_variables", "coercion_model", "latex",
        "normalize_names", "prod"
    }),
    "sage.matroids.transversal_matroid": frozenset({
        "BipartiteGraph", "Counter", "DiGraph", "MinorMatroid",
        "TransversalMatroid", "bytes_to_str", "copy", "newlabel", "str_to_bytes"
    }),
    "sage.games.hexad": frozenset({
        "GF", "MatrixSpace", "Minimog", "SR", "infinity", "matrix", "picture_set",
        "view_list"
    }),
    "sage.schemes.toric.chow_group": frozenset({
        "ChowCycle", "ChowGroup", "ChowGroupFactory", "ChowGroup_class",
        "ChowGroup_degree_class", "FGP_Element", "FGP_Module_class", "FreeModule",
        "Infinity", "QQ", "SageObject", "ToricDivisor_generic",
        "ToricVariety_field", "UniqueFactory", "WithEqualityById", "ZZ",
        "annotations", "cached_method", "flatten"
    }),
    "sage.quadratic_forms.genera.spinor_genus": frozenset({
        "AbelianGroupElement_gap", "AbelianGroupGap", "QQ", "SpinorOperator",
        "SpinorOperators", "ZZ"
    }),
    "sage.rings.polynomial.pbori.interpolate": frozenset({
        "Block", "BoolePolynomialVector", "BooleSet", "Monomial", "Polynomial",
        "Random", "Variable", "add_up_poly_list", "add_up_polynomials",
        "bench_interpolate", "clock", "declare_ring", "gen_random_o_z",
        "gen_random_poly", "generator", "interpolate", "interpolate_smallest_lex",
        "lex_groebner_basis_for_polynomial_via_variety",
        "lex_groebner_basis_points", "nf_lex_points", "variety_lex_leading_terms"
    }),
    "sage.combinat.superpartition": frozenset({
        "ClonableArray", "Composition", "EnumeratedSets", "GlobalOptions",
        "InheritComparisonClasscallMetaclass", "Integer", "Parent", "Partition",
        "Partitions", "SuperPartition", "SuperPartitions", "SuperPartitions_all",
        "SuperPartitions_n", "SuperPartitions_n_m", "UniqueRepresentation", "ZZ",
        "annotations", "chain", "reduce", "richcmp", "richcmp_method"
    }),
    "sage.matroids.gammoid": frozenset({
        "DiGraph", "Gammoid", "Matroid", "MinorMatroid"
    }),
    "sage.modules.fp_graded.free_module": frozenset({
        "CombinatorialFreeModule", "FreeGradedModule", "FreeGradedModuleElement",
        "FreeModule", "GradedModules", "Hom", "PrincipalIdealDomains",
        "cached_method", "infinity"
    }),
    "sage.rings.padics.padic_relaxed_errors": frozenset({
        "PrecisionError", "raise_error"
    }),
    "sage.combinat.cyclic_sieving_phenomenon": frozenset({
        "CyclicSievingCheck", "CyclicSievingPolynomial", "PolynomialRing", "ZZ",
        "annotations", "lcm", "orbit_decomposition"
    }),
    "sage.data_structures.stream": frozenset({
        "Action", "CoefficientRing", "DominatingAction", "FractionFieldElement",
        "FractionField_generic", "HopfAlgebrasWithBasis", "InfinitePolynomial",
        "InfinitePolynomialRing", "QuotientFields", "Stream", "Stream_add",
        "Stream_binary", "Stream_binaryCommutative", "Stream_cauchy_compose",
        "Stream_cauchy_invert", "Stream_cauchy_mul",
        "Stream_cauchy_mul_commutative", "Stream_derivative",
        "Stream_dirichlet_convolve", "Stream_dirichlet_invert", "Stream_exact",
        "Stream_function", "Stream_inexact", "Stream_infinite_operator",
        "Stream_infinite_product", "Stream_infinite_sum", "Stream_integral",
        "Stream_iterator", "Stream_lmul", "Stream_map_coefficients", "Stream_neg",
        "Stream_plethysm", "Stream_rmul", "Stream_scalar", "Stream_shift",
        "Stream_sub", "Stream_taylor", "Stream_truncated", "Stream_unary",
        "Stream_uninitialized", "Stream_zero", "UniqueRepresentation",
        "VariablePool", "ZZ", "cached_method", "divisors", "infinity",
        "lazy_attribute", "prod", "wt_int_vec_iter"
    }),
    "sage.combinat.partition_algebra": frozenset({
        "AlgebrasWithBasis", "CombinatorialFreeModule", "Graph",
        "PartitionAlgebraElement_ak", "PartitionAlgebraElement_bk",
        "PartitionAlgebraElement_generic", "PartitionAlgebraElement_pk",
        "PartitionAlgebraElement_prk", "PartitionAlgebraElement_rk",
        "PartitionAlgebraElement_sk", "PartitionAlgebraElement_tk",
        "PartitionAlgebra_ak", "PartitionAlgebra_bk", "PartitionAlgebra_generic",
        "PartitionAlgebra_pk", "PartitionAlgebra_prk", "PartitionAlgebra_rk",
        "PartitionAlgebra_sk", "PartitionAlgebra_tk", "Permutations", "QQ", "Set",
        "SetPartition", "SetPartitions", "SetPartitionsAk", "SetPartitionsAk_k",
        "SetPartitionsAkhalf_k", "SetPartitionsBk", "SetPartitionsBk_k",
        "SetPartitionsBkhalf_k", "SetPartitionsIk", "SetPartitionsIk_k",
        "SetPartitionsIkhalf_k", "SetPartitionsPRk", "SetPartitionsPRk_k",
        "SetPartitionsPRkhalf_k", "SetPartitionsPk", "SetPartitionsPk_k",
        "SetPartitionsPkhalf_k", "SetPartitionsRk", "SetPartitionsRk_k",
        "SetPartitionsRkhalf_k", "SetPartitionsSk", "SetPartitionsSk_k",
        "SetPartitionsSkhalf_k", "SetPartitionsTk", "SetPartitionsTk_k",
        "SetPartitionsTkhalf_k", "SetPartitionsXkElement", "SetPartitions_set",
        "Set_generic", "Subsets", "ZZ", "binomial", "catalan_number", "ceil",
        "factorial", "identity", "is_planar", "pair_to_graph", "propagating_number",
        "set_partition_composition", "to_graph", "to_set_partition"
    }),
    "sage.combinat.knutson_tao_puzzles": frozenset({
        "BK_pieces", "DeltaPiece", "Graphics", "HT_grassmannian_pieces",
        "HT_two_step_pieces", "H_grassmannian_pieces", "H_two_step_pieces",
        "Integers", "K_grassmannian_pieces", "KnutsonTaoPuzzleSolver", "NablaPiece",
        "PolynomialRing", "PuzzleFilling", "PuzzlePiece", "PuzzlePieces",
        "RhombusPiece", "UniqueRepresentation", "annotations", "cached_method",
        "graphics_array", "line", "polygon", "text"
    }),
    "sage.rings.qqbar": frozenset({
        "AA", "AAPoly", "AA_0", "AA_golden_ratio", "AA_hash_offset", "ANBinaryExpr",
        "ANDescr", "ANExtensionElement", "ANRational", "ANRoot", "ANUnaryExpr",
        "Action", "AlgebraicField", "AlgebraicField_common", "AlgebraicGenerator",
        "AlgebraicGeneratorRelation", "AlgebraicNumber",
        "AlgebraicNumberPowQQAction", "AlgebraicNumber_base",
        "AlgebraicPolynomialTracker", "AlgebraicReal", "AlgebraicRealField", "CC",
        "CIF", "ComplexIntervalField", "ComplexIntervalFieldElement",
        "CyclotomicField", "GaussianField", "GlobalOptions", "NumberField",
        "NumberFieldElement_gaussian", "Polynomial", "PolynomialRing", "QQ", "QQ_0",
        "QQ_1", "QQ_1_2", "QQ_1_4", "QQbar", "QQbarPoly", "QQbar_I",
        "QQbar_I_generator", "QQbar_I_nf", "QQbar_hash_offset", "QQx", "QQx_x",
        "QQxy", "QQxy_x", "QQxy_y", "QQy", "QQy_y", "RIF", "RR", "RR_1_10",
        "RealBallField", "RealIntervalField", "RealIntervalFieldElement",
        "RealIntervalField_class", "SageObject", "Singleton", "ZZ", "ZZX_x",
        "algebraic_generator_counter", "an_binop_element", "an_binop_expr",
        "an_binop_rational", "cached_method", "clear_denominators",
        "cmp_elements_with_same_minpoly", "conjugate_expand", "conjugate_shrink",
        "do_polred", "factor", "find_zero_result", "get_AA_golden_ratio",
        "is_AlgebraicNumber", "is_AlgebraicReal", "isolating_interval",
        "lazy_string", "number_field_elements_from_algebraics", "op_EQ", "op_GT",
        "op_NE", "parent_is_numerical", "parent_is_real_numerical", "prec_seq",
        "qq_generator", "rational_exact_root", "rich_to_bool", "richcmp",
        "richcmp_method", "richcmp_not_equal", "short_prec_seq", "t1", "t2",
        "tail_prec_seq"
    }),
    "sage.rings.complex_mpc": frozenset({
        "AA", "CCtoMPC", "CDF", "CLF", "ComplexField_class", "Expression", "Fields",
        "INTEGERtoMPC", "MPComplexField", "MPComplexField_class", "MPComplexNumber",
        "MPCtoMPC", "MPFRtoMPC", "PariError", "QQbar", "RLF", "bytes_to_str",
        "cache", "complex_ten", "digit_ten", "exponent_ten", "have_same_parent",
        "imaginary_ten", "late_import", "mpfr_prec_max", "mpfr_prec_min",
        "number_ten", "parent", "pari_gen", "re_complex_ten", "revop",
        "rich_to_bool", "rich_to_bool_sgn", "richcmp", "richcmp_not_equal", "sign",
        "split_complex_string", "str_to_bytes"
    }),
    "sage.rings.polynomial.toy_buchberger": frozenset({
        "LCM", "LM", "LT", "Sequence", "buchberger", "buchberger_improved",
        "inter_reduction", "select", "spol", "update"
    }),
    "sage.rings.ideal": frozenset({
        "Cyclic", "FieldIdeal", "Fields", "GeneratorType", "Ideal",
        "Ideal_fractional", "Ideal_generic", "Ideal_pid", "Ideal_principal",
        "Katsura", "MonoidElement", "Rings", "Sequence", "is_Ideal", "op_NE",
        "rich_to_bool"
    }),
    "sage.structure.element": frozenset({
        "AdditiveGroupElement", "AlgebraElement", "CommutativeAlgebraElement",
        "CommutativeRingElement", "DedekindDomainElement", "Element",
        "ElementWithCachedMethod", "EuclideanDomainElement", "Expression",
        "FieldElement", "InfinityElement", "IntegralDomainElement", "LazyFormat",
        "Matrix", "ModuleElement", "ModuleElementWithMutability", "MonoidElement",
        "MultiplicativeGroupElement", "PrincipalIdealDomainElement", "RingElement",
        "Vector", "bin_op", "canonical_coercion", "coerce_binop", "coercion_model",
        "coercion_traceback", "deprecation", "digits_to_bits", "get_coercion_model",
        "have_same_parent", "is_AdditiveGroupElement", "is_AlgebraElement",
        "is_CommutativeAlgebraElement", "is_CommutativeRingElement",
        "is_DedekindDomainElement", "is_Element", "is_EuclideanDomainElement",
        "is_FieldElement", "is_InfinityElement", "is_IntegralDomainElement",
        "is_Matrix", "is_ModuleElement", "is_MonoidElement",
        "is_MultiplicativeGroupElement", "is_PrincipalIdealDomainElement",
        "is_RingElement", "is_Vector", "make_element", "parent", "revop",
        "rich_to_bool", "rich_to_bool_sgn", "richcmp", "richcmp_not_equal",
        "sage_wraps"
    }),
    "sage.graphs.base.sparse_graph": frozenset({
        "SparseGraph", "SparseGraphBackend", "bytes_to_str", "str_to_bytes"
    }),
    "sage.graphs.base.graph_backends": frozenset({
        "GenericGraphBackend", "bytes_to_str", "str_to_bytes",
        "unpickle_graph_backend"
    }),
    "sage.graphs.base.dense_graph": frozenset({
        "DenseGraph", "DenseGraphBackend", "bytes_to_str", "str_to_bytes"
    }),
    "sage.combinat.misc": frozenset({
        "DoublyLinkedList", "Infinity", "IterableFunctionCall",
        "check_integer_list_constraints", "prod", "umbral_operation"
    }),
    "sage.graphs.genus": frozenset({
        "Graph", "bytes_to_str", "simple_connected_genus_backtracker",
        "simple_connected_graph_genus", "str_to_bytes"
    }),
    "sage.modular.pollack_stevens.fund_domain": frozenset({
        "Id", "Integer", "M2Z", "M2ZSpace", "ManinRelations", "MatrixSpace",
        "P1List", "PollackStevensModularDomain", "QQ", "SageObject", "Sigma0", "ZZ",
        "basic_hecke_matrix", "cached_method", "minone_inf_path", "sig", "t00",
        "t01", "t10", "t11", "tau"
    }),
    "sage.graphs.cliquer": frozenset({
        "all_cliques", "all_max_clique", "clique_number", "max_clique"
    }),
    "sage.misc.mrange": frozenset({
        "cantor_product", "cartesian_product_iterator", "mrange", "mrange_iter",
        "prod", "xmrange", "xmrange_iter"
    }),
    "sage.combinat.free_dendriform_algebra": frozenset({
        "Alphabet", "BinaryTree", "BinaryTrees", "CoercionException",
        "CombinatorialFreeModule", "CompositeConstructionFunctor",
        "ConstructionFunctor", "DendriformFunctor", "Family",
        "FreeDendriformAlgebra", "Functor", "HopfAlgebras",
        "IdentityConstructionFunctor", "Infinity", "LabelledBinaryTree",
        "LabelledBinaryTrees", "Rings", "cached_method", "lazy_attribute"
    }),
    "sage.modular.abvar.cuspidal_subgroup": frozenset({
        "Cusp", "CuspidalSubgroup", "CuspidalSubgroup_generic", "FiniteSubgroup",
        "Gamma0_class", "QQ", "RationalCuspSubgroup", "RationalCuspidalSubgroup",
        "ZZ", "infinity", "is_rational_cusp_gamma0", "matrix"
    }),
    "sage.modular.modform.space": frozenset({
        "Integer", "ModularFormElement", "ModularFormsSpace", "Newform",
        "PlusInfinity", "PowerSeries", "PowerSeriesRing", "QQ", "Rings", "Sequence",
        "WARN", "ZZ", "cached_method", "contains_each", "gcd",
        "is_ModularFormsSpace", "rich_to_bool", "richcmp", "richcmp_method",
        "richcmp_not_equal", "zero_matrix"
    }),
    "sage.modular.modsym.modsym": frozenset({
        "CommutativeRings", "Fields", "Integer", "ModularSymbols",
        "ModularSymbols_clear_cache", "RationalField", "canonical_parameters"
    }),
    "sage.rings.integer": frozenset({
        "GCD_list", "Integer", "IntegerWrapper", "bytes_to_str", "coerce_binop",
        "free_integer_pool", "have_same_parent", "initialized", "int_to_Z",
        "is_Integer", "make_integer", "n_factor_to_list", "new_gen_from_integer",
        "objtogen", "parent", "pari_divisors_small", "pari_gen", "pari_is_prime",
        "pari_is_prime_power", "revop", "rich_to_bool", "rich_to_bool_sgn",
        "richcmp", "richcmp_not_equal", "set_integer_from_gen", "str_to_bytes"
    }),
    "sage.functions.trig": frozenset({
        "Function_arccos", "Function_arccot", "Function_arccsc", "Function_arcsec",
        "Function_arcsin", "Function_arctan", "Function_arctan2", "Function_cos",
        "Function_cot", "Function_csc", "Function_sec", "Function_sin",
        "Function_tan", "GinacFunction", "acos", "acot", "acsc", "arccos", "arccot",
        "arccsc", "arcsec", "arcsin", "arctan", "arctan2", "asec", "asin", "atan",
        "atan2", "cos", "cot", "csc", "sec", "sin", "tan"
    }),
    "sage.groups.additive_abelian.additive_abelian_wrapper": frozenset({
        "AdditiveAbelianGroupWrapper", "AdditiveAbelianGroupWrapperElement",
        "Morphism", "Sequence", "UnwrappingMorphism", "ZZ", "basis_from_generators",
        "parent", "vector"
    }),
}


#: Names a listed module exports that the screen deliberately did NOT export.
#:
#: Only ever import machinery re-exported next to the mathematics --
#: `lazy_import`, `libgap` -- which the namespace scrub deletes from the
#: namespace and the validator refuses by name, so dropping one removes nothing
#: a caller had. It is recorded rather than filtered silently: the drift test
#: re-screens each module permitting exactly these names, so a Sage that adds a
#: different dangerous export to a listed module fails the screen with the new
#: name instead of dropping it quietly. A module absent from here screened clean
#: as a whole on this runtime.
STAR_EXPORT_DROPS: dict[str, frozenset[str]] = {
    "sage.combinat.knutson_tao_puzzles": frozenset({"lazy_import"}),
    "sage.combinat.matrices.latin": frozenset({"libgap"}),
    "sage.combinat.partition_algebra": frozenset({"lazy_import"}),
    "sage.data_structures.stream": frozenset({"lazy_import"}),
    "sage.graphs.generators.distance_regular": frozenset({"LazyImport", "libgap"}),
    "sage.rings.complex_mpc": frozenset({"pari"}),
    "sage.rings.polynomial.toy_buchberger": frozenset({"get_verbose"}),
}

