"""The corpus figures quoted in prose must match the sweep that produced them.

`doctest-corpus-stats.md` is regenerated by every run of the sweep. The same
numbers are also quoted as claims in `README.md`, `ROADMAP.md` and
`TESTING.md`, where nothing regenerates them -- so they drift, silently, in
the direction of looking worse than the truth or better.

They had drifted two releases by 2026-09-21: the prose said 98.83% and 98.92%
while the sweep read 98.8908% and 98.9740%. A figure nobody can check is a
figure nobody should quote, which is why this ties the prose to the artifact.

The monolithic number comes from the checked-in stats file. The passagemath
number cannot: that sweep runs in its own CI lane against a different runtime,
and its stats file is a build artifact rather than a commit. So this test
pins the monolithic figure exactly and checks the passagemath one only for
being present and plausible -- an assertion that cannot be made precisely is
better made loosely than dropped.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
STATS = ROOT / "doctest-corpus-stats.md"


#: The runtime the committed figures were measured against. The passagemath
#: CI lane runs the same sweep with `SAGEMATH_MCP_DOCTEST_STATS_FILE` pointed
#: at this very file, so during that job the file holds *its* numbers, not the
#: monolithic ones the prose quotes. Today these tests happen to run first --
#: `test_docs_corpus_figures.py` sorts before `test_sage_doctest_corpus.py` --
#: and passing on alphabetical ordering is not passing for a reason. So the
#: runtime is read out of the file and the comparison is skipped when it is
#: not the one the prose is about.
MONOLITHIC = "10.9"


def _runtime() -> str:
    text = STATS.read_text(encoding="utf-8")
    match = re.search(r"^- SageMath: (\S+)", text, re.MULTILINE)
    assert match, "doctest-corpus-stats.md no longer records its runtime"
    return match.group(1)


def _measured() -> tuple[str, int]:
    """(acceptance, refused) as the last sweep recorded them."""
    if _runtime() != MONOLITHIC:
        pytest.skip(
            f"doctest-corpus-stats.md currently holds {_runtime()} figures "
            "(the passagemath lane regenerates it in place); the prose quotes "
            f"SageMath {MONOLITHIC}"
        )
    text = STATS.read_text(encoding="utf-8")
    acceptance = re.search(r"\*\*Acceptance \(in-scope\)\*\* \| \*\*([\d.]+)%\*\*", text)
    refused = re.search(r"\| Refused \| ([\d,]+) \|", text)
    assert acceptance and refused, "doctest-corpus-stats.md has changed shape"
    return acceptance.group(1), int(refused.group(1).replace(",", ""))


def test_the_passagemath_figure_is_quoted_somewhere() -> None:
    """Checked loosely and on every runtime: that sweep's stats file is a CI
    artifact rather than a commit, so the exact number cannot be asserted
    here -- but a document claiming a passagemath acceptance at all is
    something this test can insist on, and its absence would mean the second
    runtime had quietly stopped being reported."""
    for document in ("ROADMAP.md", "TESTING.md"):
        text = (ROOT / document).read_text(encoding="utf-8")
        assert re.search(r"passagemath", text), f"{document} no longer mentions passagemath"
        assert re.search(r"9[89]\.\d+%", text), f"{document} quotes no acceptance figure"


@pytest.mark.parametrize("document", ["ROADMAP.md", "TESTING.md"])
def test_the_exact_figure_matches_the_sweep(document: str) -> None:
    """Both quote the monolithic acceptance to four decimal places, so both
    can be checked against the artifact exactly."""
    acceptance, _ = _measured()
    prose = (ROOT / document).read_text(encoding="utf-8")
    assert f"{acceptance}%" in prose, (
        f"{document} does not quote the measured acceptance {acceptance}%. "
        "Re-read it from doctest-corpus-stats.md rather than editing the "
        "prose to whatever seems right."
    )


def test_the_readme_rounds_the_same_number() -> None:
    """The README rounds to one decimal, being a front door rather than a
    manual. It must still round *this* number."""
    acceptance, _ = _measured()
    rounded = f"{round(float(acceptance), 1):.1f}%"
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    assert rounded in readme, f"README.md does not quote {rounded}"


def test_the_readme_refusal_count_matches() -> None:
    _, refused = _measured()
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    assert f"{refused:,} in-scope refusals" in readme, (
        f"README.md does not quote {refused:,} in-scope refusals"
    )


@pytest.mark.parametrize("document", ["README.md", "ROADMAP.md"])
def test_no_document_quotes_a_wrong_refusal_count(document: str) -> None:
    """Both quote a refusal count, and only the README's was checked -- so
    ROADMAP.md carried 4,105 against a measured 4,153, a number copied from a
    note rather than read from the artifact. Checking one place and not the
    other is how the second one drifts.
    """
    _, refused = _measured()
    text = (ROOT / document).read_text(encoding="utf-8")
    for match in re.finditer(r"([\d,]{4,}) (?:in-scope )?refus", text):
        if int(match.group(1).replace(",", "")) == refused:
            continue
        # A superseded count may stay as history, on the same terms as a
        # superseded percentage: the sentence has to say when it was true.
        window = " ".join(text[max(0, match.start() - 400) : match.end() + 400].split())
        assert re.search(r"\d{4}-\d{2}-\d{2}", window), (
            f"{document} quotes {match.group(1)} refusals, which is not the "
            f"measured {refused:,}, without saying when it was true"
        )


def test_the_enforced_floor_is_quoted_and_below_the_measurement() -> None:
    """A floor quoted above the current figure would mean CI is already
    failing, and a floor nobody quotes is one nobody can hold you to."""
    acceptance, _ = _measured()
    for document in ("ROADMAP.md", "TESTING.md", "USAGE.md"):
        text = (ROOT / document).read_text(encoding="utf-8")
        if "98.50%" in text:
            break
    else:
        pytest.fail("no document states the enforced acceptance floor")
    assert float(acceptance) > 98.50


def test_a_superseded_figure_is_dated_where_it_is_kept() -> None:
    """The gap in the test above, found by reading `main` after it merged.

    Those tests check that the *measured* figure appears; they say nothing
    about other figures on the page. ROADMAP.md keeps an older pair inside a
    completed entry -- legitimate history -- but written in the present tense
    it reads as a current claim, which is the same defect in a smaller place.

    So a superseded acceptance figure may stay, provided the sentence holding
    it says when it was measured.
    """
    acceptance, _ = _measured()
    text = (ROOT / "ROADMAP.md").read_text(encoding="utf-8")
    for match in re.finditer(r"9[89]\.\d+%", text):
        if match.group(0) == f"{acceptance}%" or match.group(0) == "98.50%":
            continue
        window = " ".join(text[max(0, match.start() - 400) : match.end() + 400].split())
        assert re.search(r"measured on \d{4}-\d{2}-\d{2}|as of \d{4}-\d{2}-\d{2}", window), (
            f"ROADMAP.md quotes {match.group(0)}, which is not the measured "
            f"{acceptance}%, without saying when it was measured"
        )
