"""The corpus figures quoted in prose must match the sweep that produced them.

`doctest-corpus-stats.md` is regenerated by every run of the sweep. The same
numbers are also quoted as claims in `README.md`, `ROADMAP.md` and
`TESTING.md`, where nothing regenerates them -- so they drift, silently, in
the direction of looking worse than the truth or better.

They had drifted two releases by 2026-09-21: the prose said 98.83% and 98.92%
while the sweep read 98.8908% and 98.9740%. A figure nobody can check is a
figure nobody should quote, which is why this ties the prose to the artifact.

The monolithic number comes from the checked-in stats file. The passagemath
number cannot: that sweep runs in its own CI lane against a different runtime,
and its stats file is a build artifact rather than a commit. So this test
pins the monolithic figure exactly and checks the passagemath one only for
being present and plausible -- an assertion that cannot be made precisely is
better made loosely than dropped.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
STATS = ROOT / "doctest-corpus-stats.md"


def _measured() -> tuple[str, int]:
    """(acceptance, refused) as the last sweep recorded them."""
    text = STATS.read_text(encoding="utf-8")
    acceptance = re.search(r"\*\*Acceptance \(in-scope\)\*\* \| \*\*([\d.]+)%\*\*", text)
    refused = re.search(r"\| Refused \| ([\d,]+) \|", text)
    assert acceptance and refused, "doctest-corpus-stats.md has changed shape"
    return acceptance.group(1), int(refused.group(1).replace(",", ""))


@pytest.mark.parametrize("document", ["ROADMAP.md", "TESTING.md"])
def test_the_exact_figure_matches_the_sweep(document: str) -> None:
    """Both quote the monolithic acceptance to four decimal places, so both
    can be checked against the artifact exactly."""
    acceptance, _ = _measured()
    prose = (ROOT / document).read_text(encoding="utf-8")
    assert f"{acceptance}%" in prose, (
        f"{document} does not quote the measured acceptance {acceptance}%. "
        "Re-read it from doctest-corpus-stats.md rather than editing the "
        "prose to whatever seems right."
    )


def test_the_readme_rounds_the_same_number() -> None:
    """The README rounds to one decimal, being a front door rather than a
    manual. It must still round *this* number."""
    acceptance, _ = _measured()
    rounded = f"{round(float(acceptance), 1):.1f}%"
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    assert rounded in readme, f"README.md does not quote {rounded}"


def test_the_readme_refusal_count_matches() -> None:
    _, refused = _measured()
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    assert f"{refused:,} in-scope refusals" in readme, (
        f"README.md does not quote {refused:,} in-scope refusals"
    )


def test_the_enforced_floor_is_quoted_and_below_the_measurement() -> None:
    """A floor quoted above the current figure would mean CI is already
    failing, and a floor nobody quotes is one nobody can hold you to."""
    acceptance, _ = _measured()
    for document in ("ROADMAP.md", "TESTING.md", "USAGE.md"):
        text = (ROOT / document).read_text(encoding="utf-8")
        if "98.50%" in text:
            break
    else:
        pytest.fail("no document states the enforced acceptance floor")
    assert float(acceptance) > 98.50
