"""requirements-passagemath.txt must be exactly what uv.lock says.

Dockerfile.passagemath installs the passagemath runtime with
``pip install --require-hashes -r requirements-passagemath.txt`` so the image
gets the locked set and nothing else. That only holds while the exported file
and ``uv.lock`` agree. Both move: a pin bump edits the lock, so does a
Dependabot update or ``uv lock --upgrade``. If the export is not regenerated
(``make passagemath-lock``), the image silently installs the previous set --
or, worse, the old hashes stop matching and the build fails on a release tag.
This test makes the drift fail here instead.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
EXPORTED = ROOT / "requirements-passagemath.txt"

# uv colours its output when told to, and `FORCE_COLOR` in a developer's shell
# is enough to tell it even through a pipe. The codes then wrap the header line,
# so `# This file was autogenerated` no longer starts with `#`, the header is
# read as content, and the diff claims the export is stale when it is identical.
# Stripped here rather than only prevented below, so the comparison cannot be
# broken by any other route to colour.
_ANSI = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")

# The exact command `make passagemath-lock` runs, minus the output file: the
# header uv writes records the command, so the two are compared without it.
EXPORT_COMMAND = (
    "uv", "export", "--frozen", "--extra", "passagemath", "--no-dev",
    "--no-emit-project", "--format", "requirements.txt",
)


def _requirement_lines(text: str) -> list[str]:
    """Requirement and hash lines only: uv's header and its indented
    ``# via <parent>`` annotations are comments, not content."""
    plain = _ANSI.sub("", text)
    return [
        line.rstrip()
        for line in plain.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def test_every_requirement_is_hash_pinned() -> None:
    """--require-hashes refuses a file with any unhashed requirement; check first
    so the failure names the package rather than a pip error inside a build."""
    lines = _requirement_lines(EXPORTED.read_text(encoding="utf-8"))
    requirements = [line for line in lines if not line.lstrip().startswith("--hash=")]
    assert requirements, "the exported file has no requirements"
    for i, line in enumerate(lines):
        if line.lstrip().startswith("--hash="):
            continue
        assert line.endswith("\\"), f"requirement without a hash continuation: {line!r}"
        assert i + 1 < len(lines) and lines[i + 1].lstrip().startswith("--hash="), (
            f"requirement without a hash: {line!r}"
        )
    assert not any(line.startswith("sagemath-mcp") for line in requirements), (
        "the project itself is in the export; it is installed separately with --no-deps"
    )
    assert any(line.startswith("passagemath-standard==") for line in requirements), (
        "the passagemath extra is not in the export"
    )


def test_colour_in_uv_output_does_not_look_like_drift() -> None:
    """The failure this guards against read as "the export is stale" when the
    two files were byte-identical, which sends you to `make passagemath-lock`
    for no reason. Colour must be invisible to the comparison."""
    plain = "anyio==4.15.1 \\\n    --hash=sha256:abc\n"
    coloured = (
        "\x1b[32m# This file was autogenerated by uv\x1b[39m\n"
        "anyio==4.15.1 \\\n    --hash=sha256:abc\n"
    )
    assert _requirement_lines(coloured) == _requirement_lines(plain)


@pytest.mark.skipif(shutil.which("uv") is None, reason="uv is not on PATH")
def test_the_export_matches_the_lockfile() -> None:
    # And ask uv not to colour in the first place: NO_COLOR is the standard
    # opt-out, and FORCE_COLOR would override it, so it goes.
    env = {k: v for k, v in os.environ.items() if k not in ("FORCE_COLOR", "CLICOLOR_FORCE")}
    env["NO_COLOR"] = "1"
    result = subprocess.run(
        [*EXPORT_COMMAND],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
        timeout=120,
        env=env,
    )
    expected = _requirement_lines(result.stdout)
    actual = _requirement_lines(EXPORTED.read_text(encoding="utf-8"))
    assert actual == expected, (
        "requirements-passagemath.txt does not match uv.lock; run `make passagemath-lock` "
        "and commit the result (the Dockerfile installs from this file with --require-hashes)"
    )


def test_the_fastmcp_cap_covers_both_packages() -> None:
    """`fastmcp` and `fastmcp-slim` are released together, and capping one
    name left the other free.

    `fastmcp==3.4.7` requires `fastmcp-slim[client,server]` at the same
    version, so a bump to either alone is incoherent as well as regressed.
    Dependabot proposed exactly that in PR #144 -- `fastmcp-slim` 3.4.7 to
    4.0.5 in the hash-locked requirements the passagemath image installs,
    while `fastmcp` stayed behind. That reaches the image rather than the
    test environment, which is the half of the supply chain the lockfile
    exists to pin (REVIEW_ACTIONS 94).

    The lockfile drift test rejects the mismatch, verified by applying the
    patch and watching it fail. This checks the layer before it: Dependabot
    should not be proposing the bump at all.
    """
    import yaml

    config = yaml.safe_load((ROOT / ".github" / "dependabot.yml").read_text(encoding="utf-8"))
    # By what it manages, not by one ecosystem name: this test named "pip",
    # and item 96 moved Python to the `uv` ecosystem, so it raised
    # StopIteration instead of checking the caps it exists to check. A test
    # that breaks on a rename is better than one that silently passes, but
    # neither is what was wanted here.
    python = [
        update
        for update in config["updates"]
        if update["package-ecosystem"] in {"uv", "pip", "poetry", "pip-compile"}
    ]
    assert python, "no Python ecosystem is configured for Dependabot"
    ignored = {
        entry["dependency-name"]
        for update in python
        for entry in update.get("ignore", [])
        if "version-update:semver-major" in entry.get("update-types", [])
    }
    assert {"fastmcp", "fastmcp-slim"} <= ignored, (
        "both fastmcp packages must be capped against major bumps; "
        f"currently ignored: {sorted(ignored)}"
    )


def test_the_two_fastmcp_packages_are_pinned_together() -> None:
    """The invariant the cap protects: whatever versions are locked, the two
    must agree. A mismatch installs a wrapper against a core it was not
    released with."""
    text = (ROOT / "requirements-passagemath.txt").read_text(encoding="utf-8")
    versions = dict(re.findall(r"^(fastmcp(?:-slim)?)==(\S+?)\s", text, re.MULTILINE))
    assert set(versions) == {"fastmcp", "fastmcp-slim"}, versions
    assert versions["fastmcp"] == versions["fastmcp-slim"], (
        f"fastmcp and fastmcp-slim are locked at different versions: {versions}"
    )


def test_dependabot_updates_the_lock_and_not_the_generated_export() -> None:
    """`requirements-passagemath.txt` is derived, not authored.

    It is exported from `uv.lock` and installed by `Dockerfile.passagemath`
    with `--require-hashes`. Dependabot's `pip` ecosystem scans
    `requirements*.txt` and edited it *without* touching the lock, so every
    grouped update contradicted the lock and failed the drift test above --
    #141, #144 and #150, all red for the same structural reason.

    A dependency PR that is always red is worse than none: it teaches a
    reviewer to wave the next one through, and #141 was lifting the fastmcp
    cap (REVIEW_ACTIONS 96).

    The `uv` ecosystem updates `pyproject.toml` and `uv.lock` instead, which
    is where a version actually lives here.
    """
    import yaml

    config = yaml.safe_load((ROOT / ".github" / "dependabot.yml").read_text(encoding="utf-8"))
    ecosystems = {update["package-ecosystem"] for update in config["updates"]}
    assert "uv" in ecosystems, "Python dependencies must be managed through the uv ecosystem"
    assert "pip" not in ecosystems, (
        "the pip ecosystem scans requirements*.txt and would edit the generated "
        "export again; the only requirements file here is derived from uv.lock"
    )


def test_the_export_is_reachable_by_one_documented_command() -> None:
    """The drift test tells you to run `make passagemath-lock`. That target
    has to exist, and CONTRIBUTING has to mention it, or the instruction in a
    failing test is the only place anyone learns it."""
    makefile = (ROOT / "Makefile").read_text(encoding="utf-8")
    assert "\npassagemath-lock:" in makefile
    contributing = " ".join((ROOT / "CONTRIBUTING.md").read_text(encoding="utf-8").split())
    assert "make passagemath-lock" in contributing, (
        "CONTRIBUTING.md does not tell a contributor how to regenerate the export"
    )
