"""Regenerate src/sagemath_mcp/allowlist.py from the installed SageMath.

The allowlist is baked in rather than derived at startup: deriving it costs a
worker launch, and that cost lands inside the caller's first evaluation. The
integration test `test_the_caller_allowlist_matches_this_sage` fails when the
baked list and the installed Sage disagree, and this is how to fix that.

    docker exec sage-mcp bash -lc 'cd /workspace && sage -python \
        scripts/generate_allowlist.py > /tmp/allowlist_new.py'
    docker exec sage-mcp cat /tmp/allowlist_new.py > src/sagemath_mcp/allowlist.py

Write through a temporary file, never straight over allowlist.py: this script
imports the worker, which imports the policy, which imports the allowlist. A
shell redirect truncates the file before the import runs, and the generator then
cannot start.

Review the diff. A name that compiles, spawns a process, downloads or writes
belongs in `_DANGEROUS_SAGE_MODULES` in `_sage_worker.py`, not here.
"""

from __future__ import annotations

import math
import textwrap

from sagemath_mcp._sage_worker import _build_namespace, _restricted_builtins

HEADER = '''"""The names caller code is allowed to read.

Seven sandbox bypasses in two days had one shape between them: a name nobody had
thought to forbid. `cython`, `sh`, `gp`, `get_remote_file`, `unpickle_global`,
`compile_and_load` -- each was reachable because the rule was a denylist, and a
denylist over a namespace this size is always one name behind.

This is the other direction. A caller may read a name only if it appears here, so
anything unrecognised is refused rather than permitted. It does not retroactively
catch a dangerous name still sitting in the namespace today -- it is derived from
that namespace -- but it changes the default for everything that comes next: a
helper added by a future SageMath release is denied until someone looks at it and
adds it, rather than reachable the day it lands.

Generated by scripts/generate_allowlist.py; checked against the installed Sage by
an integration test. Do not edit by hand.

Names the caller defines -- assignments, loop variables, function arguments,
comprehension targets, `var('t')` -- are allowed without appearing here.
"""

# Sage exports Unicode mathematical names -- Greek letters and look-alikes for
# Latin ones. They are the real spellings Sage binds. The ambiguous-character
# rules are switched off for this file in pyproject.toml rather than with a
# `noqa` here: which of them fire depends on the installed Sage, so a directive
# baked into generated output goes stale as RUF100 the next time it changes.

from __future__ import annotations

ALLOWED_CALLER_NAMES: frozenset[str] = frozenset({
'''


def main() -> int:
    namespace = _build_namespace()
    names = {name for name in namespace if not name.startswith("_")}
    names |= {name for name in _restricted_builtins() if not name.startswith("_")}
    # The pure-Python worker used by the unit suite preloads `from math import *`,
    # so log10, comb and friends are legitimate names there. Including them keeps
    # one allowlist valid for both runtimes; they are ordinary maths either way.
    names |= {name for name in vars(math) if not name.startswith("_")}
    body = textwrap.fill(
        ", ".join(f'"{name}"' for name in sorted(names)),
        width=88,
        initial_indent="    ",
        subsequent_indent="    ",
    )
    print(HEADER + body + "\n})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
